# Definición de 3 variables, La primera definiendo el Nombre del aprendiz, la segunda definiendo la formacion y la tercera definiendo el numero de ficha
nombre_estudiante = input("Ingresa tu nombre: ")
Institucion = input("formacion: ")
Formacion_cursada = input("Ingrese el numero de ficha: ")

# Imprimir la información
print("EL estudiante", nombre_estudiante, "Estudia en ", Institucion, "en el programa de formacion", Formacion_cursada) 